# Linear Regression

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt

x_data = [1,2,3]
y_data = [1,2,3]
W = tf.Variable(tf.random.normal([1]), name='weight')
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Our hypothesis for linear model X * W
hypothesis = X * W
# cost/loss function
cost = tf.reduce_sum(tf.square(hypothesis - Y))
# Minimize: Gradient Descent using derivative: W -= learning_rate * derivative
learning_rate = 0.1
gradient = tf.reduce_mean((W * X - Y) * X)
descent = W - learning_rate * gradient
update = W.assign(descent)
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(21):
    sess.run(update, feed_dict={X: x_data, Y: y_data})
    print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W))

0 0.17303206 [0.888827]
1 0.049217984 [0.94070774]
2 0.013999803 [0.9683775]
3 0.003982149 [0.9831347]
4 0.0011326945 [0.9910052]
5 0.0003221865 [0.9952028]
6 9.164593e-05 [0.9974415]
7 2.6067644e-05 [0.9986355]
8 7.415664e-06 [0.9992722]
9 2.1091964e-06 [0.99961185]
10 6.000002e-07 [0.999793]
11 1.7059654e-07 [0.9998896]
12 4.8551442e-08 [0.9999411]
13 1.38024525e-08 [0.9999686]
14 3.933355e-09 [0.99998325]
15 1.1127241e-09 [0.99999106]
16 3.1832315e-10 [0.99999523]
17 9.10525e-11 [0.99999744]
18 2.5824676e-11 [0.9999986]
19 7.1622708e-12 [0.9999993]
20 1.5489832e-12 [0.99999964]


# Output when W=5

In [16]:
import tensorflow as tf
#tf Graph Input
X = [1,2,3]
Y = [1,2,3]

In [17]:
#Set wrong model weights 5
W= tf.Variable(5.0)

In [22]:
#linear model
hypothesis = X*W
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

In [25]:
#Launch the graph in a session.
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(10):
    print(step,sess.run(W))
    sess.run(train)

0 5.0
1 1.2666664
2 1.0177778
3 1.0011852
4 1.000079
5 1.0000052
6 1.0000004
7 1.0
8 1.0
9 1.0


# Hypthesis not using matrix

In [3]:
import tensorflow as tf
x1_data = [73.,93.,89.,96., 73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1+x2*w2+x3*w3+b
cost = tf.reduce_mean(tf.square(hypothesis -Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train], feed_dict={x1: x1_data,x2: x2_data,x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  33518.15 
Prediction:
 [-15.821081  -7.594969 -13.747862 -11.077925  -6.035528]
10 Cost:  9.166196 
Prediction:
 [146.12192 187.03114 178.02965 197.761   142.41252]
20 Cost:  8.830174 
Prediction:
 [146.62105 187.61382 178.61282 198.39407 142.85432]
30 Cost:  8.801003 
Prediction:
 [146.6317  187.60939 178.6175  198.39719 142.8483 ]
40 Cost:  8.771996 
Prediction:
 [146.64087 187.60324 178.62042 198.3984  142.84097]
50 Cost:  8.743169 
Prediction:
 [146.64998 187.59708 178.62332 198.3996  142.83366]
60 Cost:  8.714491 
Prediction:
 [146.65906 187.59093 178.62622 198.40079 142.82634]
70 Cost:  8.685918 
Prediction:
 [146.66815 187.58481 178.62914 198.402   142.81909]
80 Cost:  8.657557 
Prediction:
 [146.67719 187.5787  178.63202 198.40318 142.81181]
90 Cost:  8.629286 
Prediction:
 [146.6862  187.57259 178.63489 198.40436 142.80457]
100 Cost:  8.601194 
Prediction:
 [146.6952  187.56653 178.63777 198.40553 142.79738]
110 Cost:  8.573232 
Prediction:
 [146.7042  187.56047 178.6

1100 Cost:  6.4009523 
Prediction:
 [147.48721 187.0326  178.89194 198.50014 142.17203]
1110 Cost:  6.384034 
Prediction:
 [147.49416 187.02794 178.8942  198.50089 142.16666]
1120 Cost:  6.367211 
Prediction:
 [147.50107 187.02328 178.89642 198.50162 142.16129]
1130 Cost:  6.350429 
Prediction:
 [147.50797 187.01862 178.89862 198.50232 142.15594]
1140 Cost:  6.333764 
Prediction:
 [147.51486 187.014   178.90086 198.50307 142.15062]
1150 Cost:  6.317172 
Prediction:
 [147.52171 187.00937 178.90306 198.50377 142.1453 ]
1160 Cost:  6.300726 
Prediction:
 [147.52856 187.0048  178.9053  198.50453 142.14001]
1170 Cost:  6.284289 
Prediction:
 [147.53539 187.00018 178.90749 198.50523 142.1347 ]
1180 Cost:  6.2679176 
Prediction:
 [147.54222 186.99564 178.9097  198.50594 142.12947]
1190 Cost:  6.25167 
Prediction:
 [147.549   186.99104 178.91188 198.50664 142.12419]
1200 Cost:  6.2354817 
Prediction:
 [147.55577 186.98648 178.91408 198.50734 142.11896]
1210 Cost:  6.219386 
Prediction:
 [147.5

# Hypthesis using matrix

In [4]:
import tensorflow as tf
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
   cost_val, hy_val, _ = sess.run(
       [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
   if step % 10 == 0:
       print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  34853.008 
Prediction:
 [[ -8.298836]
 [-18.245636]
 [-13.416084]
 [-17.660019]
 [-13.563999]]
10 Cost:  13.678747 
Prediction:
 [[156.80406]
 [180.22208]
 [182.12381]
 [195.27997]
 [137.82182]]
20 Cost:  13.291666 
Prediction:
 [[157.2897 ]
 [180.83208]
 [182.71117]
 [195.92155]
 [138.292  ]]
30 Cost:  13.223898 
Prediction:
 [[157.27731]
 [180.84338]
 [182.70863]
 [195.92075]
 [138.30554]]
40 Cost:  13.156476 
Prediction:
 [[157.26344]
 [180.85286]
 [182.70433]
 [195.918  ]
 [138.31766]]
50 Cost:  13.089409 
Prediction:
 [[157.24962]
 [180.86234]
 [182.70006]
 [195.91528]
 [138.32974]]
60 Cost:  13.022726 
Prediction:
 [[157.23582]
 [180.87173]
 [182.69576]
 [195.91255]
 [138.3418 ]]
70 Cost:  12.956433 
Prediction:
 [[157.22206]
 [180.88113]
 [182.69153]
 [195.90984]
 [138.3538 ]]
80 Cost:  12.890439 
Prediction:
 [[157.20833]
 [180.89049]
 [182.68724]
 [195.90714]
 [138.36578]]
90 Cost:  12.824831 
Prediction:
 [[157.19466]
 [180.89986]
 [182.68301]
 [195.90446]
 [138.3777

860 Cost:  8.701567 
Prediction:
 [[156.24359]
 [181.54893]
 [182.3879 ]
 [195.71951]
 [139.2055 ]]
870 Cost:  8.658426 
Prediction:
 [[156.23248]
 [181.55653]
 [182.38445]
 [195.71738]
 [139.21516]]
880 Cost:  8.6155815 
Prediction:
 [[156.2214 ]
 [181.56409]
 [182.38101]
 [195.71527]
 [139.22478]]
890 Cost:  8.572964 
Prediction:
 [[156.21036]
 [181.57162]
 [182.37756]
 [195.71313]
 [139.23434]]
900 Cost:  8.530532 
Prediction:
 [[156.19933]
 [181.57915]
 [182.37415]
 [195.71103]
 [139.24391]]
910 Cost:  8.488379 
Prediction:
 [[156.18832]
 [181.58662]
 [182.37073]
 [195.70892]
 [139.25343]]
920 Cost:  8.446447 
Prediction:
 [[156.17738]
 [181.59412]
 [182.36734]
 [195.70683]
 [139.26295]]
930 Cost:  8.404709 
Prediction:
 [[156.16644]
 [181.60158]
 [182.36392]
 [195.70474]
 [139.27242]]
940 Cost:  8.363224 
Prediction:
 [[156.15555]
 [181.60901]
 [182.36055]
 [195.70267]
 [139.28189]]
950 Cost:  8.321951 
Prediction:
 [[156.14467]
 [181.61642]
 [182.35716]
 [195.70058]
 [139.2913 ]]

1850 Cost:  5.385703 
Prediction:
 [[155.2759 ]
 [182.20871]
 [182.08673]
 [195.53763]
 [140.04105]]
1860 Cost:  5.3603926 
Prediction:
 [[155.26736]
 [182.21452]
 [182.08406]
 [195.53606]
 [140.04837]]
1870 Cost:  5.3352194 
Prediction:
 [[155.25883]
 [182.2203 ]
 [182.0814 ]
 [195.53448]
 [140.05566]]
1880 Cost:  5.310223 
Prediction:
 [[155.25038]
 [182.22609]
 [182.07877]
 [195.53293]
 [140.06296]]
1890 Cost:  5.285284 
Prediction:
 [[155.2419 ]
 [182.23186]
 [182.0761 ]
 [195.53136]
 [140.0702 ]]
1900 Cost:  5.260562 
Prediction:
 [[155.23347]
 [182.23761]
 [182.0735 ]
 [195.52983]
 [140.07745]]
1910 Cost:  5.235922 
Prediction:
 [[155.22507]
 [182.24333]
 [182.07086]
 [195.5283 ]
 [140.0847 ]]
1920 Cost:  5.2114344 
Prediction:
 [[155.21664]
 [182.24904]
 [182.06825]
 [195.52675]
 [140.09187]]
1930 Cost:  5.187012 
Prediction:
 [[155.20827]
 [182.25476]
 [182.06561]
 [195.52522]
 [140.09906]]
1940 Cost:  5.162774 
Prediction:
 [[155.1999 ]
 [182.26044]
 [182.06299]
 [195.52368]
 